<a href="https://colab.research.google.com/github/kwon0136/Python/blob/master/190221/test1_universial_def.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype = np.float)
y = np.array([[5,6],[7,8]], dtype = np.float)
print(x)
print("")
print(y)
print("")
print(x+y)
print("")
print(np.add(x,y))
print("")
print(x-y)
print("")
print(np.subtract(x,y))
print("")
print(np.divide(x,y))
print("")
print(np.sqrt(x)) #제곱근
print("")
print(np.sum(x))
print("")
print(np.sum(x, axis=0)) #col 기준 합
print("")
print(np.sum(x, axis=1)) #row 기준 합
print("")

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]

10.0

[4. 6.]

[3. 7.]



In [0]:
print(x)
print("")
print(x.T) #transfer
print("")
z = np.array([[1,2],[3,4],[5,6]])
z.shape
print(z)
print("")
print(z.T)
print("")
print(z.T.shape)

[[1. 2.]
 [3. 4.]]

[[1. 3.]
 [2. 4.]]

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]

(2, 3)


In [0]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y1 = np.array([1,0,1])
y2 = x1 + y1
print(x1.shape)
print("")
print(y1.shape)
print("")
print(y2.shape)
print("")
print(y2)

(4, 3)

(3,)

(4, 3)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
