<a href="https://colab.research.google.com/github/kwon0136/Python/blob/master/190221/test2_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(np.amin(a,1)) # 1 --> row 기준 최소
print("")
print(np.amin(a,0)) # 0 --> col 기준 최소
print("")
print(np.max(a))
print("")
print(np.amax(a, axis=0))
print("")
print(np.amax(a, axis=1))
print("")
print(np.median(a, axis=0))
print("")
print(np.median(a, axis=1))
print("")
print(np.mean(a))
print("")
print(np.mean(a, axis=0))
print("")
print(np.mean(a, axis=1))
print("")

[3 3 2]

[2 4 3]

9

[8 7 9]

[7 8 9]

[3. 4. 5.]

[5. 4. 4.]

5.0

[4.33333333 5.         5.66666667]

[5. 5. 5.]



In [0]:
a1 = np.array([1,2,3,4])
print(np.std(a1))  # 표준편차
print(np.var(a1))  # 분산

1.118033988749895
1.25
