<a href="https://colab.research.google.com/github/kwon0136/Python/blob/master/190220/test1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

#다차원 array
b = np.array([[1,2],[3,4]])
print(b)
#c = [[1,2],[3,4]]
#print(c)
#b != c

d = np.array([1, 2, 3, 4], ndmin = 2) #차원 정의 ex.2차원
print(d)

e = np.array([1,2,3,4], dtype = complex) #type변경 ex.복소수
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 3 4]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [0]:
import numpy as np
dt = np.dtype(np.int32)
print(dt)
type(dt)

int32


numpy.dtype

In [0]:
import numpy as np
dt = np.dtype([('age',np.int8)])

a = np.array([10,20,30], dtype=np.int8)
print(a)

[10 20 30]


In [0]:
import numpy as np

a = np.array([1,2,3])
print(a.shape)
a1 = np.array([[1,2,3],[4,5,6]])
#print(a)
print(a1.shape) # 크기 



(3,)
(2, 3)


In [0]:
import numpy as np
a1 = np.array([[1,2,3],[4,5,6]])
print(a1.shape)

a1.shape = (3,2) #shape 변경
print(a1)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [0]:
import numpy as np

a3 = np.arange(24) # for문과 같은 기능
print(a3.ndim)

a3.shape = (2,4,3)
print(a3)

a4 = np.arange(24)
a5 = a4.reshape(2,4,3)
print(a5)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [0]:
import numpy as np
a = np.zeros((3,3)) #'0'으로 채운다
print(a)
print(a.dtype)

a1 = np.ones((2,2)) #'1'로 채운다
print(a1)

a2 = np.empty((3,3)) #임의의 값으로 채운다
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
import numpy as np
a = np.array([1,2,3,4,5,6], dtype=np.int8)
print(a.ndim)
print(a.dtype)
print(a.shape)

a1 = np.array([1,2,3,4], dtype=np.float)
print(a1.ndim)
print(a1.dtype)
print(a1.shape)

a2 = a1.astype(np.int16) # a2 = a1의 dtype을 'int16'으로 바꾸어 가져온다
print(a2)
print(a2.dtype)

1
int8
(6,)
1
float64
(4,)
[1 2 3 4]
int16


In [0]:
import numpy as np
#1차원을 모두 0으로 채우기
a3 = np.zeros(5)
print(a3)

#1차원을 모두 0으로 채우고 int로 정의
a4 = np.zeros((5,), dtype=np.int)
print(a4.dtype)

[0. 0. 0. 0. 0.]
int32
