<a href="https://colab.research.google.com/github/kwon0136/Python/blob/master/190220/test2_test1Re_index_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

a = np.array([1,2,3])
print(a)
a1 = np.array((1,2,3))
print(a)
a2 = np.array([1,2,3], dtype=np.float)
print(a2)
print(a2.dtype)
a3 = np.zeros((3,3))
print(a3)
print(a3.ndim)
a4 = np.zeros((3,3,3))
print(a4)
print(a4.ndim)
a5 = np.empty((2,3))
print(a5)
a5.shape = (3,2)
print(a5)
print(a5.shape)

[1 2 3]
[1 2 3]
[1. 2. 3.]
float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [0]:
#Index, Slicing --> python과 거의 동일
import numpy as np

a = np.arange(10)
#for i in range(1,10):
#    print(a[i])
a[2:]
a[0:2]
a[:3]
a[2:5]

array([2, 3, 4])

In [0]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(a.shape)
print(a.dtype)
a[0]
print(a[0:2])
print(a[0,2])
print(a[:,0]) # a의 모든 index의 index[0]값을 가져온다 ex.[1,2,3][0] == [1] / [4,5,6][0] == [4]
print(a[0:2,1:]) # a[0]부터 a[1]의 index[1:]값을 가져온다. ex. [1,2,3][1:] == [2,3]
a[0,1:2] = 100
print(a)

2
(3, 3)
int32
[[1 2 3]
 [4 5 6]]
3
[1 4 7]
[[2 3]
 [5 6]]
[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]


In [0]:
import numpy as np

a = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
a.shape
a.ndim
a[1:4]
a[1:4,1:3]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [0]:
import numpy as np
data = np.loadtxt(fname="village_population.csv", encoding="utf-8", dtype=np.str, delimiter=",", usecols=range(0,104))
type(data)
data.shape
data[0]
data[1]
data[:,0]

array(['\ufeff행정구역', '서울특별시  (1100000000)', '서울특별시 종로구 (1111000000)', ...,
       '제주특별자치도 서귀포시 대천동(5013060000)', '제주특별자치도 서귀포시 중문동(5013061000)',
       '제주특별자치도 서귀포시 예래동(5013062000)'], dtype='<U34')

In [0]:
data2 = data[1:,:]
data2.shape

(3829, 104)