<a href="https://colab.research.google.com/github/kwon0136/Python/blob/master/190220/test2_bool_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

data = np.array([[0,1,2],[3,4,5],[6,7,8]])
data.shape
data.ndim
data
print(data[0])
print(data[2])
print(data[data > 4])

print("")
data2 = np.array(['Bob','John','Bob'])
data2.dtype
data2 == 'Bob'
data ==1
data[data > 3]


#차원에 상관없이 일정
data3 = np.array([1,2,3,4,5,6,7,8,9])
data3
print(data3.ndim)
print(data3.mean()) #평균
print(data3.max()) #최대값
print(data3.min()) #최소
print(data4.sum())

print("")
data4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data4.ndim)
print(data4.mean())
print(data4.max())
print(data4.min())
print(data4.sum())

print("")
print(data4[0].mean()) #data4[0]의 평균값

[0 1 2]
[6 7 8]
[5 6 7 8]

1
5.0
9
1
45

2
5.0
9
1
45

2.0
